#     VillageDefense 3 configuration file
#
#    You can edit here the basic things of VD 3
#      Please read everything CAREFULLY!
#   You don't want to break anything, do you?
#

# Select locale of VD 3, default it's English.
# Available locales:
#    default - English language. Uses 'language.yml'.
#    de - Deutsche sprache
#    pl - Język polski
#    es - Idioma español
#    id - Bhasa Indonesia
#    fr - Langue française
#    vn - Tiếng việt
#
locale: default

# Enable bossbar support?
Bossbar-Enabled: true

# Should we hook into bungee cord? (If you wanna use arena per server option)
# You STILL need to use external addon for HUB server game signs
# Village Defense doesn't offer that addon.
# Check here for more info: https://github.com/Plajer/Village_Defense/wiki/Addons#bungee-signs-not-official
BungeeActivated: false

# Enable Inventory Manager for your games? (VERY USEFUL feature for MULTI ARENA)
# This saves inventory of players and restores it after player leaves arena.
# Saved elements: max health, health, food, experience, full inventory, armor contents, fire ticks, active potions
InventoryManager: false

# Respawn players when wave ends/starts?
Respawn-After-Wave: true

# You can create custom players permissions here.
# Player with your custom permission will get % bonus orbs
# when he lift up experience from killed zombie.
# More here: https://github.com/Plajer-Lair/Village_Defense/wiki/Commands-and-Permissions#custom-permissions
CustomPermissions:
  # Player with permission my-permission-one get 10% more orbs
  # Do not use dots (.), they won't work.
  my-permission-one: 10

# Basic permissions for game, permissions explained here: https://github.com/Plajer-Lair/Village_Defense/wiki/Commands-and-Permissions#basic-permissions
Basic-Permissions:
  Full-Games-Permission: "villagedefense.fullgames"
  Vip-Permission: "villagedefense.vip"
  Mvp-Permission: "villagedefense.mvp"
  Elite-Permission: "villagedefense.elite"
  # <arena> represents arena name (NOT MAP NAME!), for example: 'villagedefense.join.VD02'
  # use 'villagedefense.join.*' to enable access to all arenas
  Join-Permission: "villagedefense.join.<arena>"

# Should /vd leave command be blocked?
Disable-Leave-Command: false

# Commands which can be used in game, remove all of them to disable
Whitelisted-Commands:
- me
- help

# Enable this option when you're using MySQL, otherwise it won't work.
# Be careful when changing this because there is NO migrator between
# flat file and MySQL for player stats.
DatabaseActivated: false

# How many seconds game should take to start.
Starting-Waiting-Time: 60

# Speed of baby zombie. Suggested: between 1.8 and 2.0
Mini-Zombie-Speed: 2.0

# Speed of normal zombies. Suggested: between 1.2 and 1.4
Zombie-Speed: 1.3

# Enable in game rewards? See rewards.yml for more...
Rewards-Enabled: false

# Enable in game (eg. '[KIT][LEVEL] Plajer: hey') special formatting?
# Formatting is configurable in language.yml
ChatFormat-Enabled: true

# Amount of orbs given to player when game starts
Orbs-Starting-Amount: 20

# Should we block every not Village Defense associated commands in game?
Block-Commands-In-Game: true

# Should we fire some cool fireworks at location of every player after the game ends?
Firework-When-Game-Ends: true

# Should blocks behind game signs change their color based on game state?
# They will change color to:
# - white (waiting for players) stained glass
# - yellow (starting) stained glass
# - orange (in game) stained glass
# - gray (ending) stained glass
# - black (restarting) stained glass
Signs-Block-States-Enabled: true

# Are golems upgrades enabled when you click your iron golem?
# If you want to have classic Village Defense game mode i recommend to disable this.
Golem-Upgrades-Enabled: true

# Cost of golem heart upgrades
Golem-Upgrade-Tier1-Cost: 200
Golem-Upgrade-Tier2-Cost: 400
Golem-Upgrade-Tier3-Cost: 800

# Cost of golem full heal
Golem-Upgrade-Heal-Cost: 150

# Enable very simple health bar for zombies?
# They will have health instead of their names
# It will show percentage of health left.
# It's kinda buggy, you should use external plugin if you got one.
Simple-Zombie-Health-Bar-Enabled: true

# Power ups section. If you want to have classic Village Defense game mode i recommend to disable this.
Powerups:
  # Do you want to enable in-game power ups?
  # This will make zombies drop some power ups when they're killed
  # REQUIRES Holographic Displays otherwise it won't be enabled!
  Enabled: true
  # Modify powerup drop chance here
  Drop-Chance: 1.0 # 1% chance by default
  # Enable or disable specific power ups here.
  List:
    Map-Clean: true
    Double-Damage-For-Players:
      Enabled: true
      Time: 15 # seconds
    Healing-For-Players:
      Enabled: true
      Amplifier: 1
      Time-Of-Healing: 10 # seconds
    # Spawns X golems in village
    # Owner of golems is person who picked up power up
    Golem-Raid:
      Enabled: true
      Golems-Amount: 3
    # Every zombie can be killed for one hit
    One-Shot-One-Kill:
      Enabled: true
      Time: 15 # seconds

Update-Notifier:
  # Should we check for updates on plugin start/after admin join?
  # You REALLY should have this true!
  Enabled: true
  # Should we inform you when beta version is out?
  # BETA IS NOT ALWAYS AS STABLE AS NORMAL RELEASE!
  Notify-Beta-Versions: true

# Should plugin send 'debug spam' to console? IT CAN HELP IF THERE IS SOME WEIRD BEHAVIOUR OCCURRING CAUSED BY THIS PLUGIN
Debug: false

# Don't modify.
Version: 4

# No way! You've reached the end! But... where's the dragon!?
